### ISSUE TITLE
Funktion

### ISSUE THREAD

**Issue by Matze5593** [HAuser1234/Homeassistant-solar-forecast-charge-prediction#6]
It would be great if you could see the discharge time live at the current discharge power

**Comment by Matze5593** [comment]
for the parameter “#Setting: Set 12000 to your battery capacity”. Should you specify your battery capacity in Wh here?
also 19.2 kWh =19200?

**Comment by HAuser1234** [comment]
Would be a great feature! Sadly I curently do not have the time to work on more features, but the code is pretty simple!
If you want to look at doing it yourself, just make a PR and I will have a look at the changes.

**Comment by Matze5593** [comment]
![image](https://github.com/HAuser1234/Homeassistant-solar-forecast-charge-prediction/assets/55891473/1ea3195a-f806-4c7b-8e26-be86f4a7dd26)
Do you have any idea why battery SOC jumps to 100% in the evening and doesn't stay the same?
Haben Sie eine Idee, warum Batterie SOC Abends auf 100% springt und nicht den erreichten bleibt?

**Comment by Matze5593** [comment]
ich habe den code ergänzt und angepasst da ich zwei Wechselrichter habe. es wirkt so als würde es funktionieren.

I added and adapted the code because I have two inverters. It seems like it's working



```
#
# Solar battery Calc
#v 1.2
#https://github.com/HAuser1234/Homeassistant-solar-forecast-charge-prediction


sensor:
  - platform: statistics
    name: PVHausverbrauchAVG
    entity_id: sensor.load_power  # Setting: Power used by home sensor
    state_characteristic: mean
    max_age:
      minutes: 120
  - platform: statistics
    name: PVBatterieNutungAVG
    entity_id: sensor.pv_batterie_power
    state_characteristic: mean
    max_age:
      minutes: 120

template:
  - sensor:
      - name: PV Netz Power
        #friendly_name: PV export import Power
        unit_of_measurement: W
        # Setting: set export and import power
        state: "{{states.sensor.import_power.state | int(0) - states.sensor.export_power.state | int(0)}}"
      - name: PV Batterie Power
        #friendly_name: PV battery charge discharge Power
        unit_of_measurement: W
        # Setting: Set battery charge and discharge Power
        state: "{{states.sensor.battery_charging_power.state | int(0) - states.sensor.battery_discharging_power.state | int(0)}}"
      - name: PV Nacht laenge
        #friendly_name: PV night length
        unit_of_measurement: h
        state: "{% set nr = as_timestamp(state_attr('sun.sun','next_rising')) %}{% set ns = as_timestamp(state_attr('sun.sun','next_setting')) %}{% if nr > ns %}{% set nr = nr - 60*60*24 %}{% endif %}{{ (24-(ns - nr))|timestamp_custom('%H',false)|float(0)+60/(24-(ns - nr))|timestamp_custom('%m',false)|int(0)/10}}"
      - name: PV minimum Batterie Prozent
        #friendly_name: PV battery minimum charge
        unit_of_measurement: "%"
        # Setting: Set notstrom to your individual power reserve sensor or Value, Set 400w to average power use at night, set 12000 wh to your battery capacity in wh
        state: "{% set l = states.sensor.pv_nacht_laenge.state|int(0)%}{% set minChargePerc = (l*1.3*680)/19200*100+states.sensor.reserved_soc_for_backup.state|int(0) %}{{minChargePerc}}"
      - name: PV Prod bis Sonnenuntergang
        #friendly_name: PV production power till sunset
        unit_of_measurement: kWh

        state: "{% if states.sensor.total_dc_power.state | int(0) > 0 and states.sensor.total_dc_power_inv_2.state | int(0) > 0 %}
            {% set total_dc_power = states.sensor.total_dc_power.state | int(0) %}
            {% set total_dc_power_inv_2 = states.sensor.total_dc_power_inv_2.state | int(0) %}
        {% set ProdForec = (states.sensor.energy_production_today.state | int(0) - (states.sensor.daily_pv_generation.state | int(0) + states.sensor.daily_pv_generation_inv2.state | int(0)) + total_dc_power + total_dc_power_inv_2) / 1000 %}
      {% else %}
    {% set ProdForec = states.sensor.total_dc_power.state | int(0) / 1000 %}
    {% endif %}
{{ ProdForec | float(0) }}"

      - name: PV Zeit zu Start Produktion
        #friendly_name: PV time till start production
        unit_of_measurement: h
        state: "{% set toProd = ((((((state_attr('sun.sun', 'next_rising')| as_timestamp + (40*60))|as_datetime|as_local) - now()).seconds / 60) |int(0))/60) | round(2)| float(0)%}{{toProd| float(0)}}"

      - name: PV Zeit zu Ende Produktion
        #friendly_name: PV time till end of production
        unit_of_measurement: h
        state: "{% if 'above_horizon' in states('sun.sun') %} {% set endProd = ((((((state_attr('sun.sun', 'next_setting')| as_timestamp - (40*60))|as_datetime|as_local) - now()).seconds / 60) |int(0))/60)  | round(2)| float(0)%} {% else%} {% set endProd = 0 | float(0) %} {%endif%} {{endProd| float(0)}}"

        #Secondary Calculations

      - name: PV Verbrauch bis Sonnenaufgang
        #friendly_name: PV power used till sunrise
        unit_of_measurement: W
        state: "{% set useToSunRise = (states.sensor.PVHausverbrauchAVG.state | int(0))*(states.sensor.pv_zeit_zu_start_produktion.state| float(0)) %}{{useToSunRise| float(0)}}"

      - name: PV Batterie Ladezeit
        #friendly_name: PV battery charge time till full
        # setting: set 192000 wh to your battery capacity
        unit_of_measurement: h
        state: "{% if states.sensor.pv_zeit_zu_ende_produktion.state|int(0)>0 %}{% set BatChargT = ((19200-(states.sensor.battery_level.state |int(0))/100*19200)/(states.sensor.PVBatterieNutungAVG.state| float(0))) | float(0) | round(1)%}{%else%}{% set BatChargT = 0%}{%endif%}{{BatChargT| float(0)}}"
      #Tertiary Calculations

      - name: PV Batterie morgensRestladung W
        #friendly_name: PV battery left charge wh
              # setting: set 12000 wh to your battery capacity
        unit_of_measurement: W
        state: "{% set total_dc_power = states.sensor.total_dc_power.state | float(0) %}
        {% set total_dc_power_inv_2 = states.sensor.total_dc_power_inv_2.state | float(0) %}
        {% if states.sensor.total_dc_power.state | int(0) < 1 | int(0) %}
            {% set BatStateDawnW = (states.sensor.battery_level.state | int(0))/100*19200 - (states.sensor.pv_verbrauch_bis_sonnenaufgang.state | int(0)) %}
            {% set BatStateDawnW = BatStateDawnW + total_dc_power + total_dc_power_inv_2 %}
        {% else %}
            {% set BatStateDawnW = -1 %}
        {% endif %}
        {{ BatStateDawnW | float(0) }}"


      - name: PV Batterie morgensRestladung %
        #friendly_name: PV predicted battery state at morning
              # setting: set 12000 wh to your battery capacity
        unit_of_measurement: "%"
        state: "{% set total_dc_power = states.sensor.total_dc_power.state | float(0) %}
        {% set total_dc_power_inv_2 = states.sensor.total_dc_power_inv_2.state | float(0) %}
        {% if states.sensor.total_dc_power.state | int(0) < 1 %}
            {% set BatStateDawnP = ((((states.sensor.battery_level.state | int(0))/100*19200 - states.sensor.pv_verbrauch_bis_sonnenaufgang.state | int(0)) / 19200 * 100) + total_dc_power + total_dc_power_inv_2) | round(1) %}
        {% else %}
            {% set BatStateDawnP = -1 %}
        {% endif %}
        {{ BatStateDawnP | float(0) }}"

      - name: PV Batterie Ladestand Abends
        #friendly_name: PV predicted battery state at evening
              # setting: set 19200 wh to your battery capacity
        unit_of_measurement: "%"
        state: "{% if states.sensor.pv_zeit_zu_ende_produktion.state | float(0) - states.sensor.pv_batterie_ladezeit.state | float(0) > 0 %}
            {% set BatStateDusk = 100 %}
        {% else %}
            {% set BatStateDusk = (((19200 - (states.sensor.pv_zeit_zu_ende_produktion.state | float(0) - states.sensor.pv_batterie_ladezeit.state | float(0))) * (-1) * states.sensor.PVBatterieNutungAVG.state | float(0)) / 19200 * 100) | int(0) %}
        {% endif %}
        {{ BatStateDusk | float(0) }}"

      - name: PV Batterie Entladezeit
      # freundlicher Name: PV battery discharge time
        unit_of_measurement: h
        state: >
          {% if states.sensor.battery_discharging_power.state | int(0) > 0 %}
          {% set remaining_capacity = (states.sensor.battery_level.state | int(0)) / 100 * 19200 %}
          {% set discharge_time = remaining_capacity / states.sensor.PVBatterieNutungAVG.state | float(0) %}
          {{ discharge_time | round(1) }}
          {% else %}
          0
          {% endif %}
```



![image](https://github.com/HAuser1234/Homeassistant-solar-forecast-charge-prediction/assets/55891473/6e0f6c31-2c7b-4fe7-a6a9-4ffd5ab37f85)

```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Energie Dashboard
    title_tap_action:
      action: navigate
      navigation_path: /energy
    alignment: center
  - type: conditional
    conditions:
      - entity: sensor.total_dc_master_slave
        state_not: '0'
    card:
      type: grid
      cards:
        - type: custom:mushroom-template-card
          primary: Entladezeit Batterie
          secondary: '{{ states.sensor.pv_batterie_entladezeit.state }} Stunden'
          icon: mdi:timer-outline
          icon_color: |
            {% if states.sensor.pv_batterie_entladezeit.state | float(0) > 0 %}
              orange
            {% else %}
              green
            {% endif %}
          tap_action:
            action: more-info
      columns: 1
```
